### ISSUE TITLE
Task list for visit at HRW @cekees, @tridelat, @Giovanni-Cozzuto-1989

### ISSUE THREAD

**Issue by adimako** [erdc-cm/proteus#398]
List of objectives 
- [x] Look at porous media issues (two-phase flow / instabilities)
- [x] Optimise paralellisation
- [x] Finalising gmsh implementation
- [x] Look at mooring implementation and issues
- [x] Running and rerunning WSI cases (fixed / mobile)
- [x] Running and rerunning floating body cases
- [x] Finalising 2nd order generation with wavetools
 - I will tick this, as it is nearly done. We need to produce notebooks for this case as well
- [x] Finalize three-phase flow model
 - Since the model is also a two-phase flow model, we should do some verification against air/water tests
 - Decide on ordering for incrementally enabling/verifying constitutive terms (interphase momentum transfer terms*, modified  stresses, granular pressure, collisional vs. frictional, etc.)
 - *Dould check interphase momentum transfer against static  porous media  case
 - Decide  on test problems to target (e.g. sheet flow  and oscillating sheet flow experiments, beach erosion)
 - Develop slides on formulation, methods, and results
- [x] Go over  new/developing documentation standard
- [x] Discuss jupyter notebook and jupyterhub support
- [x] Discuss plans for using Chrono
- [x] See problems with bathyduck setup
- [x] Plan for cleaning up air-water-vv

**Comment by cekees** [comment]
We might want to go over the air-water-vv repository and develop a plan for cleaning up and consolidating the tests using the Context module.

**Comment by cekees** [comment]
@adimako send me a commit with the bathyduck setup

**Comment by adimako** [comment]
@adimako to talk with R.Stephenson

**Comment by cekees** [comment]
email chrono guys about python interface to chrono. @adimako talk to ship guys  at hrw about what 6DOF modeling system they use.
